### ISSUE TITLE
error at login

### ISSUE THREAD

**Issue by Daeveren** [m4xc4v413r4/m4x-EventReminder#1] opened 2018-04-11 20:51 UTC
Getting this error lately when I'm logging on each of my chars.

```
Message: ...rface\AddOns\m4x-EventReminder\m4x-EventReminder.lua:111: attempt to index field '?' (a nil value)
Time: 04/11/18 23:48:03
Count: 1
Stack: ...rface\AddOns\m4x-EventReminder\m4x-EventReminder.lua:111: attempt to index field '?' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function `origErrorHandler'
...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:645: in function <...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:607>
[C]: ?
...rface\AddOns\m4x-EventReminder\m4x-EventReminder.lua:111: in function <...rface\AddOns\m4x-EventReminder\m4x-EventReminder.lua:96>

Locals: errorMessage = "...rface\AddOns\m4x-EventReminder\m4x-EventReminder.lua:111: attempt to index field '?' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0
```

**Comment by m4xc4v413r4** [comment] 2018-04-20 14:17
What the hell, 9 days ago? I didn't get any notifications about this...

Anyway, I'm pretty sure that error is caused by addons taking too much time to load and because of that, the data not being available to the addon when it tries to get it.

I already have a 20 sec delay on the addon because addons like TSM for example, take too much time to load, those 20 sec seemed to be enough but if you want you can try to get it up a few seconds (maybe to 25 or more if you need) until I find a permanent fix for this.

If you want to change it, go [to this line](https://github.com/m4xc4v413r4/m4x-EventReminder/blob/11fabc878ead923e9385597f3c0abe3a5f3176d8/m4x-EventReminder.lua#L211) and change the "20" to a higher number to increase the delay.

**Comment by Daeveren** [comment] 2018-04-20 15:04
Ok, thanks for your reply.

**Closed as completed** 2022-01-05 13:56 UTC
